import Navbar from '@/components/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import RootProvider from '@/Redux/RootProvider'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='max-w-[1440px] mx-auto relative'>
        <RootProvider>
          <Navbar />
        {children}
        </RootProvider>
       
      </body>
    </html>
  )
}
