import Navbar from "@/components/Navbar";
import "./globals.css";
import RootProvider from "@/Redux/RootProvider";
import RootQueryProvider from "@/tanstackQuery/QueryProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <RootQueryProvider>
        <body className="max-w-[1440px] mx-auto relative">
          <RootProvider>
            <Navbar />
            {children}
          </RootProvider>
        </body>
      </RootQueryProvider>
    </html>
  );
}
