import Footer from "@/components/Footer/Footer";
import Navbar from "@/components/Navbar";
import { BiCartAlt } from "react-icons/bi";

export const metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div className=" scrollbar-thumb-orange-500 scrollbar-thin relative">
      <Navbar />
      {children}
      <div>
      <BiCartAlt/>
      </div>
      <Footer />
    </div>
  );
}
